# Generated by Django 3.1.4 on 2021-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0002_auto_20210120_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.TextField(max_length=200, verbose_name='Blog Title'),
        ),
    ]
