# Generated by Django 3.1.4 on 2021-01-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0003_auto_20210120_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(verbose_name='Put your mind'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.TextField(max_length=264, verbose_name='Blog Title'),
        ),
    ]
