# Generated by Django 3.1.4 on 2021-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0004_auto_20210120_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=264, verbose_name='Blog Title'),
        ),
    ]
