# Generated by Django 3.1.4 on 2021-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0006_auto_20210120_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
    ]
