# Generated by Django 3.1.4 on 2021-01-15 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_login', '0003_auto_20210115_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic_bg',
        ),
        migrations.CreateModel(
            name='UserProfile_bg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic_bg', models.ImageField(upload_to='profile__bg_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_bg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
