# Generated by Django 3.1.4 on 2021-01-15 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_login', '0004_auto_20210115_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile_bg',
            new_name='UserProfileBackround',
        ),
    ]
